config/routes.rb
Obtvse::Application.routes.draw do

  # Admin
  get '/admin' => 'posts#admin', as: 'admin'
  get 'logout' => 'sessions#destroy', as: 'logout'

  get '/posts(.:format)' => 'posts#index'
  get '/posts.rss' => 'posts#index', as: 'rss'

  resources :users
  resources :sessions
  resources :posts, path: '/'

  get '/:slug' => 'posts#show', as: 'post_slug'

  root to: 'posts#index'

  # Sitemap
  get "sitemap/sitemap.xml" => "sitemap#index", as: "sitemap", defaults: { format: "xml" }
end

app/models/post.rb
class Post < ActiveRecord::Base

  validates :slug, presence: true, uniqueness: true
  validates :title, presence: true

  acts_as_url :title, :url_attribute => :slug

  scope :unpublished, -> { where(draft: true) }
  scope :published, -> { where(draft: false) }
  scope :newest, -> { order('published_at desc') }
  scope :oldest, -> { order('published_at asc') }
  scope :previous, lambda { |post| where('published_at < ?', post.published_at).newest }
  scope :next, lambda { |post| where('published_at > ?', post.published_at).newest }

  before_save :update_published_at, :chronic_parse_date

  def to_param
    slug
  end

  def external?
    !url.blank?
  end

  # def published_at
  #   # read_attribute(:published_at) ? read_attribute(:published_at).to_formatted_s(:long) : ''
  # end

  private

  def chronic_parse_date
    if published_at and self.published_at_changed?
      self.published_at = Chronic.parse(published_at) if published_at.is_a? String
    end
  end

  def update_published_at
    if published_at.nil? and draft == false
      self.published_at = Time.now
    end
  end

  def draft_changed_to_false
    self.draft_changed? and self.draft_was == true
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  validates_confirmation_of :password
  validates_presence_of :password, on: :create
  validates_uniqueness_of :email

  before_create :set_username_to_email_name

  private

  def set_username_to_email_name
    self.username = email.gsub(/[@].*/, '')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :get_user
  helper_method :no_users?

  rescue_from ActiveRecord::RecordNotFound, :with => :render_not_found

  unless Rails.configuration.consider_all_requests_local
    rescue_from Exception, :with => :render_error
    rescue_from ActionController::RoutingError, :with => :render_not_found
    rescue_from ActionController::UnknownController, :with => :render_not_found
  end

  def no_users?
    User.all.count == 0
  end

  def not_found
    raise ActionController::RoutingError.new('Not Found')
  end

  def render_not_found(exception)
    logger.error "404 Not Found"
    logger.error exception
    render template: 'errors/404', status: 404 unless @not_found
  end

  def render_error(exception)
    logger.error "500 Internal Server Error"
    logger.error exception
    render template: 'errors/500', status: 500 unless @not_found
  end

  private

  def get_user
    @user = current_user || User.new
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :require_login, except: [:index, :show, :admin]
  layout 'admin', except: [:index, :show]

  def index
    @posts = Post.published.newest.page(params[:page]).per(8)

    respond_to do |format|
      format.html
      format.xml { render xml: @posts }
      format.rss { render layout: false }
    end
  end

  def show
    @single_post = true
    @post = Post.find_by_slug(params[:id]) || not_found

    not_found if @post.draft and !logged_in?

    @next = Post.next(@post).last
    @previous = Post.previous(@post).first

    respond_to do |format|
      if @post.present?
        format.html
        format.xml { render xml: @post }
      else
        format.any { render status: 404  }
      end
    end
  end

  def admin
    if logged_in?
      @no_header = true
      @post = Post.new
      @published = Post.where(draft:false).order('published_at desc')
      @drafts = Post.where(draft:true).order('updated_at desc')
    else
      if no_users?
        render 'users/create'
      else
        render 'sessions/new'
      end
    end
  end

  def new
    @post = Post.new(title: params[:title] || '')
    @post_path = '/'

    respond_to do |format|
      format.html
    end
  end

  def edit
    @post = Post.find(params[:id])
    @post_path = post_path(@post)
  end

  def create
    @post = Post.new(params.require(:post).permit!)

    respond_to do |format|
      if @post.save
        format.html { redirect_to "/edit/#{@post.id}", notice: "Post created successfully" }
        format.xml { render xml: @post, status: :created, location: @post }
        format.text { render text: @post.to_json }
      else
        format.html { render action: 'new' }
        format.xml { render xml: @post.errors, status: :unprocessable_entity}
        format.text { head :bad_request }
      end
    end
  end

  def update
    @post = params[:id].to_i.to_s == params[:id] ? Post.find(params[:id]) : Post.find_by_slug(params[:id])
    logger.info @post

    respond_to do |format|
      if @post.update_attributes(params.require(:post).permit!)
        format.html { redirect_to "/edit/#{@post.id}", notice: "Post updated successfully" }
        format.xml { head :ok }
        format.text { render text: @post.to_json }
      else
        format.html { render action: 'edit' }
        format.xml { render xml: @post.errors, status: :unprocessable_entity}
        format.text { head :bad_request }
      end
    end
  end

  def destroy
    @post = Post.find_by_slug(params[:id])
    @post.destroy
    flash[:notice] = 'Post has been deleted'

    respond_to do |format|
      format.html { redirect_to '/admin' }
      format.xml { head :ok }
    end
  end

  private

  def admin?
    session[:admin] == true
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = login(params[:email], params[:password], true)
    if user
      redirect_back_or_to root_path, notice: "Logged in!"
    else
      redirect_to root_path, alert: "Email or password was invalid."
    end
  end

  def destroy
    logout
    redirect_to root_path, notice: "Logged out!"
  end
end

app/controllers/sitemap_controller.rb
class SitemapController < ApplicationController
  def index
    @static_pages = [root_url]
    @users = User.all
    # Display all the posts in reverse chronological order
    @posts = Post.all.sort.reverse
    respond_to do |format|
      format.xml
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_login_unless_no_users

  def create
    @user = User.new(params.require(:user).permit(:email,:password,:password_confirmation))

    respond_to do |format|
      if @user.save
        auto_login @user
        format.html { redirect_to admin_path, notice: 'Welcome!' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  private

  def require_login_unless_no_users
    require_login unless no_users?
  end

end

app/helpers/application_helper.rb
require 'kramdown'

module ApplicationHelper
  def is_admin?
    logged_in?
  end

  def markdown(text)
    Kramdown::Document.new(youtube_embed(text), {
      enable_coderay: true,
      coderay_default_lang: :ruby,
      coderay_wrap: :div,
      coderay_line_numbers: :table,
      coderay_line_numbers_start: 1,
      coderay_tab_width: 2,
      coderay_css: :style,
      coderay_bold_every: 10000
    }).to_html.html_safe
  end

  def youtube_embed(str)
    output = str.lines.map do |line|
      match = nil
      match = line.match(/^http.*(?:youtu.be\/|v\/|u\/\w\/|embed\/|watch\?v=)([^#\&\?]*).*$/)

      if match
        render partial: 'youtube.html', locals: { video: match[1] }
      else
        line
      end
    end
    output.join
  end
end

app/helpers/page_title_helper.rb
module PageTitleHelper
  def html_title(content)
    if content.present?
      [content,INFO['name']].join(' - ').html_safe
    else
      INFO['name'].html_safe
    end
  end

  def page_title(content)
    @title = content || INFO['name'].html_safe
    render partial: 'name'.html_safe
  end

  def linked_title
    link_to INFO['name'].html_safe, root_path
  end
end

app/views/application/_title.html.erb
<h1><%= link_to @title, root_path %></h1>

app/views/application/_typekit.html.erb
<script type="text/javascript">
  (function() {
    var config = {
      kitId: "<%= Rails.env.development? ? 'cfy4khk' : 'rjl6eqc' %>",
      scriptTimeout: 3000
    };
    var h=document.getElementsByTagName("html")[0];h.className+=" wf-loading";var t=setTimeout(function(){h.className=h.className.replace(/(\s|^)wf-loading(\s|$)/g," ");h.className+=" wf-inactive"},config.scriptTimeout);var tk=document.createElement("script"),d=false;tk.src='//use.typekit.net/'+config.kitId+'.js';tk.type="text/javascript";tk.async="true";tk.onload=tk.onreadystatechange=function(){var a=this.readyState;if(d||a&&a!="complete"&&a!="loaded")return;d=true;clearTimeout(t);try{Typekit.load(config)}catch(b){}};var s=document.getElementsByTagName("script")[0];s.parentNode.insertBefore(tk,s)
  })();
</script>

app/views/application/_youtube.html.erb
<div class="youtube_video">
  <object width="640" height="365">
    <param name="movie" value="http://www.youtube.com/v/<%= video %>"></param>
    <param name="wmode" value="transparent"></param>
    <embed src="http://www.youtube.com/v/<%= video %>&hl=en" type="application/x-shockwave-flash" wmode="transparent" width="640" height="365"></embed>
  </object>
</div>

app/views/layouts/admin.html.slim
doctype html
html lang="en-US"
  head
    title= html_title yield(:title)
    = csrf_meta_tag
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'admin'
    = render partial: 'application/typekit'
    link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:400,700,900' rel='stylesheet' type='text/css'
  body class="admin #{action_name}"
    = render partial: 'shared/edit_button', locals: { icon: 'reorder' }
    #sheet
    #admin
      = yield
    #modal.modal
      .modal-header
        a.close data-dismiss="modal"
        h3#modal-title
      .modal-body
        p#modal-content
      .modal-footer
        a#btn-primary.btn href="#"
        a#btn-seconday.btn.btn-primary href="#"
    #null
    #line-height Lorem

app/views/layouts/application.html.slim
doctype html
/! Font thanks to Font Awesome - http://fortawesome.github.com/Font-Awesome
html lang="en-US"
  head
    title= html_title yield(:title).html_safe
    = csrf_meta_tag
    = stylesheet_link_tag 'application'
    meta content=INFO['name'] name="author"
    link href="#{rss_path}" rel="alternate" title="RSS" type="application/rss+xml"
    link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:400,700,900' rel='stylesheet' type='text/css'
    = javascript_include_tag 'application'
  body class="#{controller_name} #{action_name} #{logged_in? ? '' : 'not-'}logged-in #{no_users? ? 'no-users' : ''}"
    #sheet
    #body
      = render partial: 'shared/edit_button', locals: { icon: 'edit' }
      - unless @no_header
        header.clearfix
          = link_to 'Home', root_path, class: 'icon-home', id: 'home-link'
          #header-content
            h1= link_to INFO['name'], root_path
            p= INFO['about'].html_safe
            .twitter
              a href="https://twitter.com/#{INFO['twitter']}" class="twitter-follow-button" data-show-count="false" data-dnt="true" Follow @#{INFO['twitter']}
              javascript:
                $('#twitter-wjs').remove();
                !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");
            ul#connect.clearfix
              - if INFO['twitter']
                li= link_to "@#{INFO['twitter']}", "http://twitter.com/#{INFO['twitter']}", class: 'icon-twitter', id: 'connect-twitter'
              - if INFO['github']
                li= link_to 'github', "https://github.com/#{INFO['github']}", class: 'icon-github', id: 'connect-github'
              - if INFO['email']
                li.right= link_to 'email', "mailto:#{INFO['email']}", class: 'icon-envelope', id: 'connect-email'
              li.right= link_to 'rss', rss_path, class: 'open-external icon-rss', id: 'connect-rss'
      - if notice
        #dialog.notice.inner= notice
      - if alert
        #dialog.alert.inner= alert
      #content
        .inner
          = yield
      .avgrund-cover
    - unless logged_in?
      aside#modal-login.avgrund-popup
        - if no_users?
          = render 'users/new_form'
        - else
          = render 'sessions/new_form'
    / Google Analytics
    - if INFO['ga_id']
      javascript:
        var _gaq=[['_setAccount',' #{INFO['ga_id']} '],['_trackPageview']];
        (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
        g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
        s.parentNode.insertBefore(g,s)}(document,'script'));

app/views/posts/_editor.html.slim
- placeholder ||= 'Title here...'
= form_for @post, url: @post_path do |f|
  = render partial: 'form', locals: { f: f, placeholder: placeholder }
  #post-preview.split-section
    .inner
  #bar
    = link_to 'Back', admin_path, id: "back-button", class: 'icon-arrow-left'
    = link_to 'Preview', '#preview', id: 'preview-button', class: 'icon-eye-open'
    .middle
      #menu-date.menu
        = link_to 'Date', '#', id: 'date-button', class: 'icon-calendar'
        ul#date.sub-menu
          li
            = f.label :published_at, 'Published Date'
            = f.text_field :published_at, value: f.object.published_at
      #menu-link.menu
        = link_to 'Link', '#link', class: 'icon-link'
        ul#link.sub-menu
          li
            = f.label :slug, 'Permalink'
            = f.text_field :slug, placeholder: 'Leave blank to automatically generate'
          li
            = f.label :url, 'External URL'
            = f.text_field :url, placeholder: 'Optional'
      .menu
        = link_to 'Stats', '#stats', class: 'icon-bar-chart', id: 'stats-button'
        ul#stats.sub-menu
          li
            label Wordcount
            span#wordcount
          li
            label Views
            span#views
          li
            label Reads
            span#reads
      .menu
        - link_to 'History', '#history', class: 'icon-list'
        ul#history.sub-menu
          li= f.label :url, 'History'
          li= link_to 'Version 3', '#'
          li= link_to 'Version 2', '#'
          li= link_to 'Version 1', '#'
    .end
      = link_to 'Draft', '#', id: 'publish-button', class: 'icon-edit'
      = link_to 'Delete', @post, confirm: 'Are you sure?', method: :delete, class: 'icon-trash'
  .hide
    = f.check_box :draft
button#save-button.animated

app/views/posts/_form.html.slim
- placeholder ||= ''

#post-editor.split-section
  - if @post.errors.any?
    .notice
      - @post.errors.full_messages.each do |msg|
        = msg
  #text-title.expandingArea
    pre
      span
      br/
    = f.text_area :title, rows: 1, placeholder: placeholder
  fieldset#content-fieldset.markdown
    #text-content.expandingArea
      pre
        span
        br/
      = f.text_area :content, placeholder: 'Write post here', class: 'faded'

app/views/posts/_json.html.erb
{'<%= json.title %>':<%= json.id %>},

app/views/posts/_li.html.slim
li id="post-#{li.id}" data-id="#{li.id}" class=(li.draft? ? "draft" : "")
  = link_to li.title, edit_post_path(li.id)

app/views/posts/_post.html.slim
- collapsed ||= false
article id="post-#{post.id}" class="#{collapsed ? 'collapsed' : 'full'}"
  - if post.external?
    h1.external
      - if @single_post
        = link_to post.title, post.url
      - else
        = link_to post.title, post.url
        = link_to '⚓', post.slug, :class => 'permalink'
  - else
    h1
      - if @single_post
        = post.title
      - else
        = link_to post.title, post
  time= post.published_at ? post.published_at.to_formatted_s(:day_month_year) : ''
  - if !collapsed
    .post
      - if post.content
        = markdown(post.content)
  #edit-link.hide data-href="#{edit_post_path post.id}"

app/views/posts/_signature.html.slim
aside.signature
  |  Follow me on
  = link_to ' Twitter ', "http://twitter.com/#{INFO['twitter']}"
  | or subscribe to
  = link_to ' RSS', rss_path

app/views/posts/admin.html.slim
= content_for(:title) { "Admin" }

= form_for @post do |f|
  = render partial: 'form', locals: { f: f, placeholder: "" }

#posts
  #drafts.col.active
    h2 Drafts
    ul data-items="#{@drafts.to_json(:only => [:id, :title])}"
      = render partial: 'li', collection: @drafts
  #published.col
    h2 Live
    ul data-items="#{@published.to_json(only: [:id, :title])}"
      = render partial: 'li', collection: @published
  .hide
    = link_to '', new_post_path, id: 'new-post'

app/views/posts/edit.html.slim
= content_for(:title) { "Edit Post" }
= render 'editor'
#post data-state="#{@post.to_json}"

app/views/posts/index.html.slim
- @list = true
= render partial: @posts, locals: { collapsed: true }
= paginate @posts

app/views/posts/new.html.slim
= content_for(:title) { "New Post" }
= render 'editor'

app/views/posts/show.html.slim
= content_for(:title) { @post.title }
= content_for(:page_title) { linked_title }

= render @post
= render 'signature'

nav.history.clearfix
  = link_to "#{@next.title}".html_safe, @next, class: 'next' if @next
  = link_to "#{@previous.title}".html_safe, @previous, class: 'prev' if @previous

app/views/shared/_edit_button.html.slim
a#edit-button href="/admin" data-target="#modal-login" class="icon-#{icon}" data-no-turbolink="true"

app/views/shared/_error_messages.html.erb
<% if error_messages.errors.any? %>
  <div class="error-messages">
    <ul>
      <% for message in error_messages.errors.full_messages %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_error_messages.html.slim
- if error_messages.errors.any?
  .error-messages
    ul
      - for message in error_messages.errors.full_messages
        li <%= message %>

app/views/users/_new_form.html.erb
<%= form_for @user do |f| %>
  <h3>Set up your account</h3>
  <%= render partial: 'shared/error_messages', object: @user %>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="actions"><%= f.submit %></div>
<% end %>

app/views/users/create.html.slim
- if no_users?
  = render 'users/new_form'

app/views/users/new.html.slim
= render 'new_form'